[semver:minor] Improvements to sonar-analysis and integration-tests

diff --git a/src/jobs/integration-tests.yml b/src/jobs/integration-tests.yml
--- a/src/jobs/integration-tests.yml
+++ b/src/jobs/integration-tests.yml
@@ -1,10 +1,12 @@
 description: >
   Runs the integration testing suite
-  The test container must contain a folder at: /home/jahians/results, this folder must contain:
+  At the end of its execution, the test container must contain a folder at: /home/jahians/results, this folder must contain:
    - A marker file (test_success or test_failure) indicating the outcome of the run
    - Run reports, in json format, in a reports/ folder
    - Run reports, in XML format, in a xml_reports/ folder
    - A installed-jahia-modules.json generated by jahia-reporter and containing installed modules
+  The job supports start and stop scripts that would be executed in-lieu of docker-compose up.
+  This optional approach is useful if there is a need to spin-up complex cluster environments.
 
 parameters:
   resource_class:
@@ -54,6 +56,10 @@ parameters:
     type: string
     default: "root1234"
     description: "Jahia root password"
+  jahia_cluster_enabled:
+    type: boolean
+    default: false
+    description: "Run Jahia in cluster mode"
   tests_image:
     type: string
     default: "modules-tests"
@@ -68,7 +74,7 @@ parameters:
     description: "Branch containing the tests (if different from current)"
   jahia_license:
     type: env_var_name
-    default: JAHIA_LICENSE_801_FULL
+    default: JAHIA_LICENSE_8x_FULL
     description: "Base64 encoded License"
   jcustomer_image:
     type: string
@@ -96,7 +102,7 @@ parameters:
   slack_webhook_notifications:
     type: env_var_name
     default: SLACK_WEBHOOK_QA_NOTIFICATIONS
-    description: "Webhook to be used for failyre notifications"
+    description: "Webhook to be used for failure notifications"
   slack_webhook_notifications_all:
     type: env_var_name
     default: SLACK_WEBHOOK_QA_NOTIFICATIONS_ALL
@@ -125,6 +131,18 @@ parameters:
     type: env_var_name
     default: TESTRAIL_PASSWORD
     description: "Testtrail Password"
+  ci_startup_script:
+    type: string
+    default: "ci.startup.sh"
+    description: "Startup script to use in-lieu of docker-compose up."
+  ci_postrun_script:
+    type: string
+    default: "ci.postrun.sh"
+    description: "Script to run prior to saving the artifacts"
+  no_output_timeout:
+    type: string
+    default: "10m"
+    description: "Elapsed time the command can run without output. Since different modules are going to have different runtime, this allow fine-tuning per module."
 
 working_directory: << parameters.working_directory >>
 
@@ -145,7 +163,8 @@ steps:
       command: |
         echo "export MANIFEST=<< parameters.tests_manifest >>" >> $BASH_ENV
         echo "export JAHIA_IMAGE=<< parameters.jahia_image >>" >> $BASH_ENV
-        echo "export JAHIA_LICENSE=<< parameters.jahia_license >>" >> $BASH_ENV
+        echo "export JAHIA_LICENSE=${<< parameters.jahia_license >>}" >> $BASH_ENV
+        echo "export JAHIA_CLUSTER_ENABLED=<< parameters.jahia_cluster_enabled >>" >> $BASH_ENV
         echo "export TESTS_IMAGE=<< parameters.tests_image >>" >> $BASH_ENV
         echo "export JCUSTOMER_IMAGE=<< parameters.jcustomer_image >>" >> $BASH_ENV
         echo "export ELASTICSEARCH_IMAGE=<< parameters.elasticsearch_image >>" >> $BASH_ENV
@@ -176,7 +195,14 @@ steps:
       name: Preparing build artifacts
       command: |
         if [ << parameters.should_skip_artifacts >> == false ]; then
-          sudo cp -r /home/circleci/source/target/*.jar << parameters.tests_path >>artifacts/
+          find . -type f -path '*/target/*-SNAPSHOT.jar' -exec cp '{}' << parameters.tests_path >>artifacts/ ';' || :
+          if [ -d ./build-dependencies/ ]; then
+            mkdir -p << parameters.tests_path >>artifacts/build-dependencies
+            cp ./build-dependencies/* << parameters.tests_path >>artifacts/build-dependencies/
+            echo "Content of build-dependencies"
+            ls -lah << parameters.tests_path >>artifacts/build-dependencies/
+          fi
+          ls -lah << parameters.tests_path >>artifacts
         fi
 
   # We always build the test container from scratch
@@ -202,7 +228,7 @@ steps:
         docker images --digests --all 2>&1 | tee -a ./artifacts/docker.log
         echo "--------------------------------------------------" >> ./artifacts/docker.log
         docker pull ${JAHIA_IMAGE}
-        echo "List of docker images in local cache AFTER pull" > ./artifacts/docker.log
+        echo "List of docker images in local cache AFTER pull" >> ./artifacts/docker.log
         docker images --digests --all 2>&1 | tee -a ./artifacts/docker.log
         echo "--------------------------------------------------" >> ./artifacts/docker.log
 
@@ -221,12 +247,18 @@ steps:
   # for us will be the test container
   - run:
       name: Spin-up the containers
+      no_output_timeout: << parameters.no_output_timeout >>
       command: |
         cd << parameters.tests_path >>
         export DOCKER_CLIENT_TIMEOUT=120
         export COMPOSE_HTTP_TIMEOUT=120
         . ./set-env.sh
-        docker-compose -f << parameters.docker_compose_file >> up --abort-on-container-exit
+        if [[ -f "<< parameters.ci_startup_script >>" ]]; then
+          echo "Startup script is present"
+          bash << parameters.ci_startup_script >>
+        else
+          docker-compose -f << parameters.docker_compose_file >> up --abort-on-container-exit
+        fi
 
   - run:
       name: Export containers artifacts (reports, secreenshots, videos)
@@ -248,7 +280,7 @@ steps:
         docker logs << parameters.tests_container_name >> > ./artifacts/results/<< parameters.tests_container_name >>.log
         cp ./artifacts/docker.log ./artifacts/results/
 
-  # This is not needed since cypress is going to terminat on failure with exit code 1
+  # This is not needed since cypress is going to terminate on failure with exit code 1
   - run:
       name: Analyze Test results
       when: always
@@ -259,6 +291,23 @@ steps:
           echo "More than one failure found, sending exit signal"
           exit 1
         fi
+
+  # If a ci.postrun.sh script is present, this script is executed
+  # The main purpose of this script is to export additional artifacts,
+  # capture logs from other containers, ...
+  - run:
+      name: Execute postrun sript (if present)
+      when: always
+      command: |
+        cd << parameters.tests_path >>
+        export DOCKER_CLIENT_TIMEOUT=120
+        export COMPOSE_HTTP_TIMEOUT=120
+        . ./set-env.sh
+        if [[ -f "<< parameters.ci_postrun_script >>" ]]; then
+          echo "Postrun script is present"
+          bash << parameters.ci_postrun_script >>
+        fi
+
   - store_test_results:
       path: << parameters.tests_path >>artifacts/results/xml_reports
   - run:
